# Generated by Django 3.2.4 on 2021-06-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artista', '0001_initial'),
        ('categoria', '0001_initial'),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('lancamento', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artista', models.ManyToManyField(to='artista.Artista')),
                ('avaliacao', models.ManyToManyField(to='avaliacao.Avaliacao')),
                ('categoria', models.ManyToManyField(to='categoria.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Filmes',
                'db_table': 'filme',
            },
        ),
    ]
