# Generated by Django 3.2.4 on 2021-06-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='avaliacao',
        ),
    ]
