# Generated by Django 3.2.4 on 2021-06-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nome_artistico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome artístico')),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artistas',
                'db_table': 'artista',
            },
        ),
    ]
