# Generated by Django 3.2.4 on 2021-06-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_remove_filme_avaliacao'),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='filme_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filme.filme'),
            preserve_default=False,
        ),
    ]
